parameters:
  chartjs.global.animation: chartjs.animation
  chartjs.global.layout: chartjs.layout
  chartjs.global.legend: chartjs.legend
  chartjs.global.title: chartjs.title

services:
  app.chartjs.twig_extension:
       class:  Aldaflux\ChartjsBundle\Twig\chartjsExtension
       arguments: ['@service_container']
       public: false
       tags:
         - { name: twig.extension }

#  app.chartjs.controller:
#       class: Aldaflux\ChartjsBundle\Controller\ChartjsController
#       public: true
#       tags: ['controller.service_arguments']
#       calls:
#           - [setContainer, ["@service_container"]]
       
       